### ISSUE TITLE
When we set the custom dialog instance it never gets dismissed. 

### ISSUE THREAD

**Issue by jrcacd** [marcoscgdev/RateDialog#3]
RateDialog rateDialog = new RateDialog(this, "custom_rate_dialog_key");

**Comment by marcoscgdev** [comment]
I'm experiencing the same problem, I'll take a look at it, thanks for the report! 😄

**Comment by marcoscgdev** [comment]
Fixed in [version 1.0.7](https://github.com/marcoscgdev/RateDialog/releases/tag/1.0.7). Thank you! 😄
